### ISSUE TITLE
When recording using mp4 format, there is a shift between video and audio.

### ISSUE THREAD

**Issue by FredBezies** [dvershinin/green-recorder#11]
Hello.

I noticed this behavior while recording a video for some tests.

Audio seems to start two or three seconds before related video is rendered.

I attached two videos of a game in Vice. You can hear the title music two or three seconds before the title screen is shown.

I'm facing this behaviour in both Wayland and X11. I compressed the file using zip, mp4 file were marked as corrcupted :(
[wayland.zip](https://github.com/dvershinin/green-recorder/files/6309236/wayland.zip)
[x11.zip](https://github.com/dvershinin/green-recorder/files/6309237/x11.zip)

**Comment by dvershinin** [comment]
@FredBezies I couldn't actually reproduce this, but what I did see were sporadic invalid moov atom errors...

I believe this is due to FFmpeg being killed not gracefully and so I tried to add some code to do it in a better fashion.

See if there's an improvement with the latest commit.

**Comment by FredBezies** [comment]
> @FredBezies I couldn't actually reproduce this, but what I did see were sporadic invalid moov atom errors...
> 
> I believe this is due to FFmpeg being killed not gracefully and so I tried to add some code to do it in a better fashion.
> 
> See if there's an improvement with the latest commit.

Looks like it is fixed. No more shift between sound and picture. Thanks.
