### ISSUE TITLE
when using pipewire, pacmd is not available (but pactl is !)

### ISSUE THREAD

**Issue by CircleCode** [dvershinin/green-recorder#12]
in `recorder/recorder.py`, you use `pacmd list-sources | grep -e device.description`, which does not work with pipewire.
The same result is, however, available with pulseaudio and pipewire if you use `pactl list sources  | grep -e device.description`

Note : I do not know what is the expected output of `pacmd list-sources | grep -e device.string` (and `pactl list sources | grep -e device.string` gives no output on my system). However,it appears that `audiosourcesids` is never used…

**Comment by dvershinin** [comment]
Fixed in 3.2.10
